//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_Emp_Legal_Sec
    {
        public decimal EmpID { get; set; }
        public string FullName { get; set; }
        public string DeptName { get; set; }
        public decimal DeptID { get; set; }
    }
}
