//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Com_Unit_Master
    {
        public Nullable<long> ID { get; set; }
        public decimal UnitCode { get; set; }
        public string UnitName { get; set; }
        public decimal CompanyCode { get; set; }
        public string CompanyName { get; set; }
    }
}
