//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpVPL_Compliance_Master
    {
        public decimal CID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Name { get; set; }
        public string Regulate_For { get; set; }
        public string Regulate_Ref { get; set; }
        public string Frequency { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> Alertbefore { get; set; }
        public Nullable<decimal> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrIP { get; set; }
        public Nullable<int> Isactive { get; set; }
    }
}
