//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPL_Compliance_Schedule_Report
    {
        public decimal CID { get; set; }
        public decimal Transid { get; set; }
        public string ComplianceDate { get; set; }
        public decimal CStatus { get; set; }
        public string Descript { get; set; }
        public string FullName { get; set; }
        public string DeptName { get; set; }
        public string UnitName { get; set; }
        public string color { get; set; }
        public string dt { get; set; }
    }
}
