//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPL_Compliance_Scheduling
    {
        public decimal Transid { get; set; }
        public Nullable<decimal> CID { get; set; }
        public Nullable<System.DateTime> UpdateFrom { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<System.DateTime> ComplianceDate { get; set; }
        public Nullable<System.DateTime> GDate { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<decimal> Crby { get; set; }
        public string CrIP { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<decimal> FDID_SD { get; set; }
    
        public virtual VPL_Compliance_Master VPL_Compliance_Master { get; set; }
    }
}
