//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPL_Compliance_Schedule_Status_ALL
    {
        public long ID { get; set; }
        public string Udate { get; set; }
        public Nullable<int> TID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<decimal> ScheduledID { get; set; }
        public Nullable<decimal> CStatus { get; set; }
        public string Descript { get; set; }
        public string FilePath { get; set; }
        public Nullable<decimal> CrBy { get; set; }
        public Nullable<System.DateTime> Crdate { get; set; }
        public string CRIP { get; set; }
        public Nullable<int> isactive { get; set; }
        public Nullable<System.DateTime> ComplianceDate { get; set; }
        public string FullName { get; set; }
        public string DeptName { get; set; }
        public string DesignName { get; set; }
        public string UnitName { get; set; }
        public string Name { get; set; }
        public decimal compid { get; set; }
        public decimal Transid { get; set; }
        public Nullable<int> Flag { get; set; }
    }
}
