//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPL_Compliance_Status
    {
        public int TID { get; set; }
        public Nullable<int> CID { get; set; }
        public Nullable<decimal> ScheduledID { get; set; }
        public Nullable<decimal> CStatus { get; set; }
        public string Descript { get; set; }
        public string FilePath { get; set; }
        public Nullable<decimal> CrBy { get; set; }
        public Nullable<System.DateTime> Crdate { get; set; }
        public string CRIP { get; set; }
        public Nullable<int> isactive { get; set; }
    }
}
