//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPL_Compliance_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VPL_Compliance_Master()
        {
            this.VPL_Compliance_AlertTo = new HashSet<VPL_Compliance_AlertTo>();
            this.VPL_Compliance_InfoRequired = new HashSet<VPL_Compliance_InfoRequired>();
            this.VPL_Compliance_Responsibility = new HashSet<VPL_Compliance_Responsibility>();
            this.VPL_Compliance_Scheduling = new HashSet<VPL_Compliance_Scheduling>();
        }
    
        public decimal CID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Name { get; set; }
        public string Regulate_For { get; set; }
        public string Regulate_Ref { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> Alertbefore { get; set; }
        public Nullable<decimal> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrIP { get; set; }
        public Nullable<int> Isactive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VPL_Compliance_AlertTo> VPL_Compliance_AlertTo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VPL_Compliance_InfoRequired> VPL_Compliance_InfoRequired { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VPL_Compliance_Responsibility> VPL_Compliance_Responsibility { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VPL_Compliance_Scheduling> VPL_Compliance_Scheduling { get; set; }
    }
}
