//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPL_HR_UserDetails
    {
        public decimal TransID { get; set; }
        public string UserID { get; set; }
        public decimal RoleID { get; set; }
        public string Active { get; set; }
        public string CrBy { get; set; }
        public System.DateTime CrDate { get; set; }
        public Nullable<int> RoleType { get; set; }
    }
}
