//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPL_User_App_Auth
    {
        public decimal User_App_Authid { get; set; }
        public Nullable<int> AppID { get; set; }
        public Nullable<decimal> EMPID { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<decimal> Crby { get; set; }
        public Nullable<System.DateTime> Crdate { get; set; }
    }
}
