//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPL_HR_RoleMaster
    {
        public decimal RoleID { get; set; }
        public string RoleDesc { get; set; }
        public string Active { get; set; }
        public string CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
    }
}
