//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPLCompliance_dashboard_Details
    {
        public Nullable<long> ID { get; set; }
        public string Deadlinea { get; set; }
        public decimal CID { get; set; }
        public Nullable<int> DeptID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> UnitID { get; set; }
        public string Name { get; set; }
        public string Regulate_For { get; set; }
        public string Regulate_Ref { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<int> Alertbefore { get; set; }
        public Nullable<decimal> CrBy { get; set; }
        public Nullable<System.DateTime> CrDate { get; set; }
        public string CrIP { get; set; }
        public Nullable<int> Isactive { get; set; }
        public string CompanyName { get; set; }
        public string UnitName { get; set; }
        public string DeptName { get; set; }
        public string FullName { get; set; }
        public decimal responsiblemep { get; set; }
        public string FrequencyName { get; set; }
        public string color { get; set; }
    }
}
