//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_DashboardUndatedCase_Details
    {
        public Nullable<long> sr_no { get; set; }
        public string Petitioner { get; set; }
        public string Respondent { get; set; }
        public string Case_no { get; set; }
        public string Court { get; set; }
        public string Nature_of_Case { get; set; }
        public string Amount { get; set; }
        public string Last_Date { get; set; }
        public string Next_Date { get; set; }
        public string Status { get; set; }
        public string TextUp { get; set; }
    }
}
